coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: frontend
      paths:
        - frontend/
      statuses:
        - type: project
          target: 60%
    - name: backend
      paths:
        - backend/
      statuses:
        - type: project
          target: 60%
github_checks:
  annotations: true
  